from __future__ import annotations

from typing import Protocol

from shea.app.contracts import AdapterResult, ExecutionContract
from shea.app.ports.process import AdapterContext


class FilesystemControlPort(Protocol):
    """EP §8.3 — filesystem operations under scope + verified path identity."""

    name: str

    def inspect(self, contract: ExecutionContract, ctx: AdapterContext) -> AdapterResult: ...
    def read(self, contract: ExecutionContract, ctx: AdapterContext) -> AdapterResult: ...
    def write(self, contract: ExecutionContract, ctx: AdapterContext) -> AdapterResult: ...
    def create(self, contract: ExecutionContract, ctx: AdapterContext) -> AdapterResult: ...
    def delete(self, contract: ExecutionContract, ctx: AdapterContext) -> AdapterResult: ...
    def copy(self, contract: ExecutionContract, ctx: AdapterContext) -> AdapterResult: ...
    def move(self, contract: ExecutionContract, ctx: AdapterContext) -> AdapterResult: ...